Repository fac-31/Pro0623-ObsidianTwoPointOPointO, pull requests merged in 2025-07, with the labels that each got.

#31 Tailwind CSS installation
  package-lock.json
  package.json
  src/app.css
  src/routes/+layout.svelte
  src/routes/+page.svelte
  vite.config.ts
Labels: Review effort 3/5

#51 Gemini XML file
  GEMINI.xml
Labels: Review effort 1/5

#53 fix(ci): updates deploy to deployment in package.json
  package.json
Labels: Review effort 1/5

#56 ci: changing to main for the push event in attempt at version bug fix
  .github/workflows/pull_request_template.md
  .github/workflows/semantic-release.yaml
  package.json
Labels: Review effort 1/5

#63 Feature: Public /worlds Page
  src/hooks.server.ts
  src/routes/worlds/+page.svelte
  src/routes/worlds/+page.ts
  src/routes/worlds/+server.ts
  src/test/e2e/worlds-page.spec.ts
Labels: enhancement

#97 ci(server.py): changes values in uvicorn run function to match deploy…
  src/python/__pycache__/server.cpython-313.pyc
  src/python/__pycache__/world_build.cpython-313.pyc
  src/python/requirements.txt
  src/python/server.py
  src/python/world_build.py
Labels: Review effort 2/5
